import { Router } from 'express';
import authRoutes from './modules/auth/auth.routes';
import salonRoutes from './modules/salons/salon.routes';
import staffRoutes from './modules/staff/staff.routes';
import serviceRoutes from './modules/services/service.routes';
import customerRoutes from './modules/customers/customer.routes';
import appointmentRoutes from './modules/appointments/appointment.routes';
import billingRoutes from './modules/billing/billing.routes';
import dashboardRoutes from './modules/dashboard/dashboard.routes';
import expenseRoutes from './modules/expenses/expense.routes';
import inventoryRoutes from './modules/inventory/inventory.routes';
import attendanceRoutes from './modules/attendance/attendance.routes';
import commissionRoutes from './modules/commission/commission.routes';
import loyaltyRoutes from './modules/loyalty/loyalty.routes';
import reportRoutes from './modules/reports/report.routes';
import notificationRoutes from './modules/notifications/notification.routes';
import subscriptionRoutes from './modules/subscriptions/subscription.routes';
import analyticsRoutes from './modules/analytics/analytics.routes';
import adminRoutes from './modules/admin/admin.routes';

export const router = Router();

router.use('/auth', authRoutes);
router.use('/salons', salonRoutes);
router.use('/staff', staffRoutes);
router.use('/services', serviceRoutes);
router.use('/customers', customerRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/billing', billingRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/expenses', expenseRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/commission', commissionRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/reports', reportRoutes);
router.use('/notifications', notificationRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/admin', adminRoutes);
